# Generated by Django 5.0.6 on 2024-05-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_book_price_alter_book_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='unit_price',
        ),
    ]
